name: Angular 15
on: workflow_dispatch
jobs:
  angular-15:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: packages/angular15
          start: npm start
          wait-on: 'http://localhost:4200'
      - name: curl
        if: always()
        run: scripts/curl.sh 4200
