name: Angular 15 workaround
on: workflow_dispatch
jobs:
  angular-15:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: packages/angular15
          start: npm start
          # Angular does not respond to localhost through
          # IPv4 loopback address 127.0.0.1
          # wait for IPv6 loopback address ::1 instead
          wait-on: 'http://[::1]:4200'
      - name: curl
        if: always()
        run: scripts/curl.sh 4200
