name: Gatsby
on: workflow_dispatch
jobs:
  gatsby:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: packages/gatsby
          start: npm start
          wait-on: 'http://localhost:8000'
      - name: curl
        if: always()
        run: scripts/curl.sh 8000
