name: Gatsby workaround
on: workflow_dispatch
jobs:
  gatsby:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: packages/gatsby
          start: npm start
          # Gatsby does not respond to localhost through
          # IPv4 loopback address 127.0.0.1
          # wait for IPv6 loopback address ::1 instead
          wait-on: 'http://[::1]:8000'
      - name: curl
        if: always()
        run: scripts/curl.sh 8000
