name: Vite
on: workflow_dispatch
jobs:
  vite:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: packages/vite
          start: npm start
          wait-on: 'http://localhost:5173'
      - name: curl
        if: always()
        run: scripts/curl.sh 5173
