name: workaround
on:
  workflow_dispatch:

jobs:

  angular:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: packages/angular
          start: npm start
          # Angular does not respond to localhost through
          # IPv4 loopback address 127.0.0.1
          # wait for IPv6 loopback address ::1 instead
          wait-on: 'http://[::1]:4200'
      - name: curl
        if: always()
        run: scripts/curl.sh 4200

  vite:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: packages/vite
          # Vite does not respond to localhost through
          # IPv4 loopback address 127.0.0.1
          # using npm start or npx vite
          # use npx vite --host instead, then it will listen
          # on IPv4 and IPv6
          start: npx vite --host
          wait-on: 'http://localhost:5173'
      - name: curl
        if: always()
        run: scripts/curl.sh 5173
